language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
- node_modules/protractor/bin/webdriver-manager update
script:
- gulp test
addons:
  sauce_connect: true
env:
  global:
  - secure: N/MkuwlF5cpWEUIezXxUqTqVitSIx40bHxNxFr8Yvn6DpAhP5gzangmshs5J1FebcTUyTYR4GvzJyHwrhGgZJcMWeYa1ov03I2DR5lp1FKglWIjyxsn3pdG52kh2ypirEPv+fcbsYz2zZ9O9TGkif4Xoka8Z7HiZMkAQYk534fM=
  - secure: OnJ3oJMTiAnyftEAAAICu/qmyko/zXI31hg5NZcLoEWXtlD+9fELLwLK39ynr5JpzPRoAx9g+sT8KnBYe4v/3d/Yg6GW1H841MzQUxDQGd956tc0PZDbZoGrAWCJf6Y6W2/Pw2g7/XzXWYAE5eG6GZIMRmCUcP4LkHEwOvwwVug=
